const Data = [
  {
    tag1: "25% off",
    tag2: " Honeymoon",
    tag3: "Package Add ons ",
    src: " ",
    header: "Land of lama - Spiti Valley Volvo ",
    day: "5 Night/6 Days",
    place: "Ex-Chandigarh ",
    city1: " Delhi(2N) ",
    city2: "Manali(1N)",
    city3: "Dharamshala(4N) ",
    span: "+2 ",
    facility: "  Hotels, Flight, Meals, Volvo, Sightseeing ",
    oldPrice: "₹20,999",
    newPrice: "₹15,999",
    span2: "Per Person",
    saveMsg: "you saved ₹5,000"
  },
  {
    tag1: "25% off",
    tag2: " Honeymoon",
    tag3: "Package Add ons ",
    src: " ",
    header: "Land of lama - Spiti Valley Volvo ",
    day: "5 Night/6 Days",
    place: "Ex-Chandigarh ",
    city1: " Delhi(2N) ",
    city2: "Manali(1N)",
    city3: "Dharamshala(4N) ",
    span: "+2 ",
    facility: "  Hotels, Flight, Meals, Volvo, Sightseeing ",
    oldPrice: "₹20,999",
    newPrice: "₹15,999",
    span2: "Per Person",
    saveMsg: "you saved ₹5,000"
  },
  {
    tag1: "25% off",
    tag2: " Honeymoon",
    tag3: "Package Add ons ",
    src: " ",
    header: "Land of lama - Spiti Valley Volvo ",
    day: "5 Night/6 Days",
    place: "Ex-Chandigarh ",
    city1: " Delhi(2N) ",
    city2: "Manali(1N)",
    city3: "Dharamshala(4N) ",
    span: "+2 ",
    facility: "  Hotels, Flight, Meals, Volvo, Sightseeing ",
    oldPrice: "₹20,999",
    newPrice: "₹15,999",
    span2: "Per Person",
    saveMsg: "you saved ₹5,000"
  },
  {
    tag1: "25% off",
    tag2: " Honeymoon",
    tag3: "Package Add ons ",
    src: " ",
    header: "Land of lama - Spiti Valley Volvo ",
    day: "5 Night/6 Days",
    place: "Ex-Chandigarh ",
    city1: " Delhi(2N) ",
    city2: "Manali(1N)",
    city3: "Dharamshala(4N) ",
    span: "+2 ",
    facility: "  Hotels, Flight, Meals, Volvo, Sightseeing ",
    oldPrice: "₹20,999",
    newPrice: "₹15,999",
    span2: "Per Person",
    saveMsg: "you saved ₹5,000"
  }
];

export default Data;
